webtalk_init -webtalk_dir /home/baotran/Desktop/ReponayKphaiChuyende/Assignments/Week4/RTL/RGB_to_Gray.sim/sim_1/behav/xsim/xsim.dir/RGB_to_Gray_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Mar 26 22:08:38 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "27f91f54-33eb-4819-926f-7d9fc4a1d93f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9e1c4ee2b2ef4d61b9da7348b9d2d988" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "64" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3616.760 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "30 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.04_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "124424_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2056759199 -regid "" -xml /home/baotran/Desktop/ReponayKphaiChuyende/Assignments/Week4/RTL/RGB_to_Gray.sim/sim_1/behav/xsim/xsim.dir/RGB_to_Gray_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/baotran/Desktop/ReponayKphaiChuyende/Assignments/Week4/RTL/RGB_to_Gray.sim/sim_1/behav/xsim/xsim.dir/RGB_to_Gray_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/baotran/Desktop/ReponayKphaiChuyende/Assignments/Week4/RTL/RGB_to_Gray.sim/sim_1/behav/xsim/xsim.dir/RGB_to_Gray_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
